# Generated by Django 3.2.12 on 2022-02-08 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_participant_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('min_price', models.IntegerField(null=True)),
                ('images', models.FileField(null=True, upload_to='')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.sub_category')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.session_time')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.status')),
            ],
        ),
    ]
