# Generated by Django 3.2.12 on 2022-02-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_product12'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product12',
        ),
    ]
