# Generated by Django 3.2.12 on 2022-02-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='image',
            field=models.ImageField(upload_to='shop/images'),
        ),
    ]
