# Generated by Django 3.2.12 on 2022-02-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
