# Generated by Django 3.2.12 on 2022-02-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0019_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
