# Generated by Django 3.2.12 on 2022-02-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0020_alter_student_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
