# Generated by Django 3.2 on 2022-03-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0025_auto_20220302_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='temp',
        ),
    ]
