# Generated by Django 3.2 on 2022-03-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0026_remove_product_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
